// lib/features/client/presentation/screens/training_plan_screen.dart

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../controllers/client_training_plan_controller.dart';

class TrainingPlanScreen extends StatefulWidget {
  final String token;
  final VoidCallback? onBack;
  const TrainingPlanScreen({super.key, required this.token, this.onBack});

  @override
  State<TrainingPlanScreen> createState() => _TrainingPlanScreenState();
}

class _TrainingPlanScreenState extends State<TrainingPlanScreen> {
  late ClientTrainingPlanController _ctrl;

  @override
  void initState() {
    super.initState();
    _ctrl = ClientTrainingPlanController();
    _ctrl.addListener(_onError);
    _ctrl.loadActivePlan(widget.token);
  }

  void _onError() {
    if (_ctrl.errorMessage != null && mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(_ctrl.errorMessage!),
          backgroundColor: Colors.red,
        ),
      );
      _ctrl.errorMessage = null;
    }
  }

  @override
  void dispose() {
    _ctrl.removeListener(_onError);
    _ctrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider.value(
      value: _ctrl,
      child: Scaffold(
        backgroundColor: const Color(0xFFF3F4F6), // Light background
        appBar: AppBar(
          backgroundColor: Colors.white,
          elevation: 0.5,
          leading: widget.onBack != null
              ? IconButton(
                  icon: const Icon(Icons.arrow_back, color: Colors.black),
                  onPressed: widget.onBack,
                )
              : null,
          title: const Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'AI Training Plans',
                style: TextStyle(
                  color: Colors.black,
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 0.5,
                ),
              ),
              Text(
                'Personalized workouts generated by Gemini AI',
                style: TextStyle(color: Color(0xFF6B7280), fontSize: 11),
              ),
            ],
          ),
        ),
        body: Consumer<ClientTrainingPlanController>(
          builder: (context, ctrl, _) {
            if (ctrl.isLoading) {
              return const Center(
                child: CircularProgressIndicator(color: Color(0xFF4F46E5)),
              );
            }

            if (ctrl.isGenerating) {
              return _buildGeneratingLoader();
            }

            if (ctrl.activePlan == null) {
              return _buildGenerationForm(ctrl);
            }

            return _buildActivePlanView(ctrl);
          },
        ),
      ),
    );
  }

  // ── AI Generation Loader ──────────────────────────────────────────────────
  Widget _buildGeneratingLoader() {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              padding: const EdgeInsets.all(24),
              decoration: const BoxDecoration(
                color: Colors.white,
                shape: BoxShape.circle,
                boxShadow: [
                  BoxShadow(
                    color: Color(0x1F4F46E5),
                    blurRadius: 30,
                    spreadRadius: 5,
                  ),
                ],
              ),
              child: const SizedBox(
                width: 60,
                height: 60,
                child: CircularProgressIndicator(
                  color: Color(0xFF4F46E5),
                  strokeWidth: 4,
                ),
              ),
            ),
            const SizedBox(height: 32),
            const Text(
              'Your Training Plan is Being Generated',
              textAlign: TextAlign.center,
              style: TextStyle(
                color: Colors.black,
                fontSize: 22,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 8),
            const Text(
              'Analyzing your fitness goals, level, and equipment to design the optimal training plan.',
              textAlign: TextAlign.center,
              style: TextStyle(color: Color(0xFF6B7280), fontSize: 13),
            ),
          ],
        ),
      ),
    );
  }

  // ── Generation Form ────────────────────────────────────────────────────────
  Widget _buildGenerationForm(ClientTrainingPlanController ctrl) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Banner Card
          Container(
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              gradient: const LinearGradient(
                colors: [Color(0xFF6366F1), Color(0xFF4F46E5)],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              borderRadius: BorderRadius.circular(16),
            ),
            child: const Row(
              children: [
                Icon(Icons.auto_awesome, color: Colors.white, size: 36),
                SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'AI Personal Trainer',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      Text(
                        'Tell us about your fitness targets, and we will formulate a personalized gym program based on real available equipment.',
                        style: TextStyle(
                          color: Color(0xFFE2E8F0),
                          fontSize: 12,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 24),

          // Goals
          _buildFormSectionTitle('1. What is your fitness goal?'),
          _buildGoalSelector(ctrl),
          const SizedBox(height: 20),

          // Experience Level
          _buildFormSectionTitle('2. Select your experience level'),
          _buildLevelSelector(ctrl),
          const SizedBox(height: 20),

          // Duration & Frequency Row
          Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildFormSectionTitle('3. Duration (Weeks)'),
                    _buildWeeksDropdown(ctrl),
                  ],
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildFormSectionTitle('4. Workouts / Week'),
                    _buildDaysDropdown(ctrl),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 20),

          // Available Equipment
          _buildFormSectionTitle('5. What equipment do you have?'),
          _buildEquipmentSelector(ctrl),
          const SizedBox(height: 20),

          // Injuries & Limitations
          _buildFormSectionTitle('6. Injuries, pain, or physical limitations'),
          TextField(
            controller: ctrl.injuriesController,
            maxLines: 2,
            style: const TextStyle(color: Colors.black, fontSize: 14),
            decoration: InputDecoration(
              hintText: 'e.g. Knee pain, lower back stiffness, none...',
              hintStyle: const TextStyle(
                color: Color(0xFF9CA3AF),
                fontSize: 13,
              ),
              filled: true,
              fillColor: const Color(0xFFF9FAFB),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Color(0xFFD1D5DB)),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Color(0xFFD1D5DB)),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Color(0xFF4F46E5)),
              ),
            ),
          ),
          const SizedBox(height: 28),

          // Generate Button
          SizedBox(
            width: double.infinity,
            height: 56,
            child: ElevatedButton.icon(
              onPressed: () async {
                final success = await ctrl.generatePlan(widget.token);
                if (success && mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(
                      content: Text('AI training plan generated successfully!'),
                      backgroundColor: Color(0xFF10B981),
                    ),
                  );
                } else if (!success && mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(
                      content: Text(ctrl.errorMessage ?? 'Generation failed'),
                      backgroundColor: Colors.red,
                    ),
                  );
                }
              },
              icon: const Icon(Icons.bolt, color: Colors.white, size: 24),
              label: const Text(
                'Generate Program',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 16,
                  fontWeight: FontWeight.bold,
                ),
              ),
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF4F46E5), // Indigo
                elevation: 2,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(14),
                ),
              ),
            ),
          ),
          const SizedBox(height: 32),
        ],
      ),
    );
  }

  Widget _buildFormSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0, left: 4),
      child: Text(
        title,
        style: const TextStyle(
          color: Color(0xFF111827),
          fontSize: 14,
          fontWeight: FontWeight.bold,
        ),
      ),
    );
  }

  Widget _buildGoalSelector(ClientTrainingPlanController ctrl) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFD1D5DB)),
      ),
      child: DropdownButtonFormField<String>(
        initialValue: ctrl.selectedGoal,
        dropdownColor: Colors.white,
        icon: const Icon(Icons.arrow_drop_down, color: Color(0xFF6B7280)),
        decoration: const InputDecoration(border: InputBorder.none),
        style: const TextStyle(color: Colors.black, fontSize: 14),
        items: ctrl.goals
            .map(
              (g) => DropdownMenuItem(
                value: g,
                child: Text(g, style: const TextStyle(color: Colors.black)),
              ),
            )
            .toList(),
        onChanged: (val) => ctrl.setGoal(val!),
      ),
    );
  }

  Widget _buildLevelSelector(ClientTrainingPlanController ctrl) {
    return Row(
      children: ctrl.levels.map((lvl) {
        final isSelected = ctrl.selectedLevel == lvl;
        return Expanded(
          child: GestureDetector(
            onTap: () => ctrl.setLevel(lvl),
            child: Container(
              margin: const EdgeInsets.symmetric(horizontal: 4),
              padding: const EdgeInsets.symmetric(vertical: 14),
              decoration: BoxDecoration(
                color: isSelected ? const Color(0xFFEEF2FF) : Colors.white,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(
                  color: isSelected
                      ? const Color(0xFF4F46E5)
                      : const Color(0xFFD1D5DB),
                  width: isSelected ? 2 : 1,
                ),
              ),
              child: Text(
                lvl[0].toUpperCase() + lvl.substring(1),
                textAlign: TextAlign.center,
                style: TextStyle(
                  color: isSelected ? const Color(0xFF4F46E5) : Colors.black,
                  fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                ),
              ),
            ),
          ),
        );
      }).toList(),
    );
  }

  Widget _buildWeeksDropdown(ClientTrainingPlanController ctrl) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFD1D5DB)),
      ),
      child: DropdownButtonFormField<int>(
        initialValue: ctrl.selectedWeeks,
        dropdownColor: Colors.white,
        icon: const Icon(Icons.arrow_drop_down, color: Color(0xFF6B7280)),
        decoration: const InputDecoration(border: InputBorder.none),
        style: const TextStyle(color: Colors.black, fontSize: 14),
        items: ctrl.weekOptions
            .map(
              (w) => DropdownMenuItem(
                value: w,
                child: Text(
                  '$w Weeks',
                  style: const TextStyle(color: Colors.black),
                ),
              ),
            )
            .toList(),
        onChanged: (val) => ctrl.setWeeks(val!),
      ),
    );
  }

  Widget _buildDaysDropdown(ClientTrainingPlanController ctrl) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFD1D5DB)),
      ),
      child: DropdownButtonFormField<int>(
        initialValue: ctrl.selectedDaysPerWeek,
        dropdownColor: Colors.white,
        icon: const Icon(Icons.arrow_drop_down, color: Color(0xFF6B7280)),
        decoration: const InputDecoration(border: InputBorder.none),
        style: const TextStyle(color: Colors.black, fontSize: 14),
        items: ctrl.daysPerWeekOptions
            .map(
              (d) => DropdownMenuItem(
                value: d,
                child: Text(
                  '$d Days',
                  style: const TextStyle(color: Colors.black),
                ),
              ),
            )
            .toList(),
        onChanged: (val) => ctrl.setDaysPerWeek(val!),
      ),
    );
  }

  Widget _buildEquipmentSelector(ClientTrainingPlanController ctrl) {
    return Column(
      children: ctrl.equipmentOptions.map((eq) {
        final isSelected = ctrl.selectedEquipment == eq;
        return GestureDetector(
          onTap: () => ctrl.setEquipment(eq),
          child: Container(
            margin: const EdgeInsets.only(bottom: 10),
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: isSelected ? const Color(0xFFEEF2FF) : Colors.white,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: isSelected
                    ? const Color(0xFF4F46E5)
                    : const Color(0xFFD1D5DB),
                width: isSelected ? 2 : 1,
              ),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  eq,
                  style: TextStyle(
                    color: isSelected ? const Color(0xFF4F46E5) : Colors.black,
                    fontWeight: isSelected
                        ? FontWeight.bold
                        : FontWeight.normal,
                  ),
                ),
                Icon(
                  isSelected
                      ? Icons.check_circle
                      : Icons.radio_button_unchecked,
                  color: isSelected
                      ? const Color(0xFF4F46E5)
                      : const Color(0xFF9CA3AF),
                  size: 20,
                ),
              ],
            ),
          ),
        );
      }).toList(),
    );
  }

  // ── Active Plan View ───────────────────────────────────────────────────────
  Widget _buildActivePlanView(ClientTrainingPlanController ctrl) {
    final plan = ctrl.activePlan!;

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Plan summary card
          Container(
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: const Color(0xFFE5E7EB)),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x0A000000),
                  blurRadius: 10,
                  offset: Offset(0, 4),
                ),
              ],
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Expanded(
                      child: Text(
                        plan.title,
                        style: const TextStyle(
                          color: Colors.black,
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                    IconButton(
                      icon: const Icon(
                        Icons.download_rounded,
                        color: Color(0xFF4F46E5),
                      ),
                      onPressed: () => ctrl.downloadPlanPdf(widget.token),
                      tooltip: 'Download PDF',
                    ),
                    IconButton(
                      icon: const Icon(Icons.delete_outline, color: Colors.red),
                      onPressed: () async {
                        final confirm = await _showConfirm(
                          'Delete Plan',
                          'Are you sure you want to delete this training plan? This will archive your progress.',
                        );
                        if (confirm == true) {
                          await ctrl.deletePlan(widget.token, plan.planID);
                        }
                      },
                    ),
                  ],
                ),
                const SizedBox(height: 8),
                Row(
                  children: [
                    _buildPill(Icons.fitness_center, plan.goal),
                    const SizedBox(width: 8),
                    _buildPill(Icons.trending_up, plan.level ?? 'General'),
                    const SizedBox(width: 8),
                    _buildPill(Icons.date_range, '${plan.weeks} Weeks'),
                  ],
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),

          // Weeks Horizontal bar
          const Text(
            'SELECT WEEK',
            style: TextStyle(
              color: Color(0xFF6B7280),
              fontSize: 11,
              fontWeight: FontWeight.bold,
              letterSpacing: 1,
            ),
          ),
          const SizedBox(height: 8),
          _buildWeeksSelector(ctrl),
          const SizedBox(height: 16),

          // Days detailed list
          _buildDaysWorkoutsList(ctrl),

          const SizedBox(height: 24),
          // Complete entire plan button
          SizedBox(
            width: double.infinity,
            height: 54,
            child: OutlinedButton(
              onPressed: () async {
                final confirm = await _showConfirm(
                  'Complete Program',
                  'Excellent job! Do you want to mark this entire program as completed?',
                );
                if (confirm == true) {
                  final success = await ctrl.completePlan(widget.token);
                  if (success && mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content: Text('Plan completed! Congratulations!'),
                      ),
                    );
                  } else if (!success && mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: Text(
                          ctrl.errorMessage ?? 'Failed to complete plan.',
                        ),
                        backgroundColor: Colors.red,
                      ),
                    );
                  }
                }
              },
              style: OutlinedButton.styleFrom(
                side: const BorderSide(color: Color(0xFF4F46E5), width: 1.5),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
              child: const Text(
                'Complete Program',
                style: TextStyle(
                  color: Color(0xFF4F46E5),
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          ),
          const SizedBox(height: 32),
        ],
      ),
    );
  }

  Widget _buildPill(IconData icon, String label) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
      decoration: BoxDecoration(
        color: const Color(0xFFF3F4F6),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFE5E7EB)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, color: const Color(0xFF4F46E5), size: 12),
          const SizedBox(width: 4),
          Text(
            label,
            style: const TextStyle(color: Colors.black87, fontSize: 11),
          ),
        ],
      ),
    );
  }

  Widget _buildWeeksSelector(ClientTrainingPlanController ctrl) {
    final plan = ctrl.activePlan!;
    return SizedBox(
      height: 48,
      child: ListView.builder(
        scrollDirection: Axis.horizontal,
        itemCount: plan.plan.length,
        itemBuilder: (context, index) {
          final wNum = plan.plan[index].week;
          final isSelected = ctrl.selectedWeekNumber == wNum;
          return GestureDetector(
            onTap: () => ctrl.setSelectedWeek(wNum),
            child: Container(
              margin: const EdgeInsets.only(right: 8),
              padding: const EdgeInsets.symmetric(horizontal: 16),
              alignment: Alignment.center,
              decoration: BoxDecoration(
                color: isSelected ? const Color(0xFF4F46E5) : Colors.white,
                borderRadius: BorderRadius.circular(24),
                border: Border.all(
                  color: isSelected
                      ? const Color(0xFF4F46E5)
                      : const Color(0xFFD1D5DB),
                ),
              ),
              child: Text(
                'Week $wNum',
                style: TextStyle(
                  color: isSelected ? Colors.white : Colors.black,
                  fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                  decoration:
                      (plan.plan[index].days.isNotEmpty &&
                          plan.plan[index].days.every((d) => d.isCompleted))
                      ? TextDecoration.lineThrough
                      : null,
                ),
              ),
            ),
          );
        },
      ),
    );
  }

  Widget _buildDaysWorkoutsList(ClientTrainingPlanController ctrl) {
    if (ctrl.activePlan!.plan.isEmpty) {
      return const Center(
        child: Padding(
          padding: EdgeInsets.all(20),
          child: Text(
            'The AI generated an incomplete or incorrectly formatted plan. Please delete this plan and generate a new one.',
            textAlign: TextAlign.center,
            style: TextStyle(color: Colors.red, fontSize: 14),
          ),
        ),
      );
    }

    final week = ctrl.activePlan!.plan.firstWhere(
      (w) => w.week == ctrl.selectedWeekNumber,
      orElse: () => ctrl.activePlan!.plan.first,
    );

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (week.theme != null && week.theme!.trim().isNotEmpty) ...[
          Container(
            padding: const EdgeInsets.all(12),
            margin: const EdgeInsets.only(bottom: 16),
            width: double.infinity,
            decoration: BoxDecoration(
              color: const Color(0xFFEEF2FF),
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: const Color(0xFFC7D2FE)),
            ),
            child: Text(
              'Theme: ${week.theme}',
              style: const TextStyle(
                color: Color(0xFF4F46E5),
                fontSize: 13,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ],
        ListView.builder(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          itemCount: week.days.length,
          itemBuilder: (context, dayIndex) {
            final day = week.days[dayIndex];
            final doneExercises = day.exercises
                .where((e) => e.isCompleted)
                .length;
            final totalExercises = day.exercises.length;
            final pct = totalExercises > 0
                ? (doneExercises / totalExercises)
                : 0.0;

            return Container(
              margin: const EdgeInsets.only(bottom: 16),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(16),
                border: Border.all(
                  color: day.isCompleted
                      ? const Color(0xFF10B981).withValues(alpha: 0.4)
                      : const Color(0xFFE5E7EB),
                ),
                boxShadow: const [
                  BoxShadow(
                    color: Color(0x05000000),
                    blurRadius: 10,
                    offset: Offset(0, 4),
                  ),
                ],
              ),
              child: Material(
                color: Colors.transparent,
                child: Theme(
                  data: Theme.of(
                    context,
                  ).copyWith(dividerColor: Colors.transparent),
                  child: ExpansionTile(
                    collapsedIconColor: Colors.black,
                    iconColor: Colors.black,
                    title: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              day.day.toLowerCase().startsWith('day')
                                  ? day.day
                                  : 'Day ${day.day}',
                              style: const TextStyle(
                                color: Colors.black,
                                fontSize: 16,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                            Text(
                              day.focus,
                              style: const TextStyle(
                                color: Color(0xFF6B7280),
                                fontSize: 12,
                              ),
                            ),
                          ],
                        ),
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.end,
                          children: [
                            Text(
                              '$doneExercises/$totalExercises done',
                              style: const TextStyle(
                                color: Color(0xFF4F46E5),
                                fontSize: 11,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                            const SizedBox(height: 4),
                            SizedBox(
                              width: 60,
                              height: 4,
                              child: LinearProgressIndicator(
                                value: pct,
                                backgroundColor: const Color(0xFFF3F4F6),
                                color: const Color(0xFF4F46E5),
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                    children: [
                      Padding(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 16,
                          vertical: 8,
                        ),
                        child: Column(
                          children: [
                            if (day.notes != null &&
                                day.notes!.trim().isNotEmpty) ...[
                              Container(
                                padding: const EdgeInsets.all(10),
                                width: double.infinity,
                                decoration: BoxDecoration(
                                  color: const Color(0xFFF9FAFB),
                                  borderRadius: BorderRadius.circular(8),
                                  border: Border.all(
                                    color: const Color(0xFFE5E7EB),
                                  ),
                                ),
                                child: Text(
                                  'Day Notes: ${day.notes}',
                                  style: const TextStyle(
                                    color: Color(0xFF6B7280),
                                    fontSize: 11,
                                    fontStyle: FontStyle.italic,
                                  ),
                                ),
                              ),
                              const SizedBox(height: 12),
                            ],

                            // Exercises
                            ...List.generate(day.exercises.length, (exIndex) {
                              final ex = day.exercises[exIndex];
                              return Container(
                                margin: const EdgeInsets.only(bottom: 8),
                                padding: const EdgeInsets.all(12),
                                decoration: BoxDecoration(
                                  color: const Color(0xFFF9FAFB),
                                  borderRadius: BorderRadius.circular(10),
                                  border: Border.all(
                                    color: ex.isCompleted
                                        ? const Color(
                                            0xFF10B981,
                                          ).withValues(alpha: 0.2)
                                        : const Color(0xFFE5E7EB),
                                  ),
                                ),
                                child: Row(
                                  children: [
                                    Checkbox(
                                      value: ex.isCompleted,
                                      activeColor: const Color(0xFF4F46E5),
                                      checkColor: Colors.white,
                                      side: const BorderSide(
                                        color: Color(0xFF9CA3AF),
                                      ),
                                      onChanged: (_) =>
                                          ctrl.toggleExerciseCompletion(
                                            dayIndex,
                                            exIndex,
                                          ),
                                    ),
                                    const SizedBox(width: 8),
                                    Expanded(
                                      child: Column(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            ex.name,
                                            style: TextStyle(
                                              color: Colors.black87,
                                              fontWeight: FontWeight.bold,
                                              decoration: ex.isCompleted
                                                  ? TextDecoration.lineThrough
                                                  : null,
                                            ),
                                          ),
                                          Row(
                                            children: [
                                              Text(
                                                'Sets: ${ex.sets}',
                                                style: const TextStyle(
                                                  color: Color(0xFF6B7280),
                                                  fontSize: 11,
                                                ),
                                              ),
                                              const SizedBox(width: 12),
                                              Text(
                                                'Reps: ${ex.reps}',
                                                style: const TextStyle(
                                                  color: Color(0xFF6B7280),
                                                  fontSize: 11,
                                                ),
                                              ),
                                            ],
                                          ),
                                          if (ex.notes != null &&
                                              ex.notes!.trim().isNotEmpty) ...[
                                            Text(
                                              'Note: ${ex.notes}',
                                              style: const TextStyle(
                                                color: Color(0xFF9CA3AF),
                                                fontSize: 10,
                                              ),
                                            ),
                                          ],
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              );
                            }),
                            const SizedBox(height: 12),

                            // Log day complete button
                            if (!day.isCompleted) ...[
                              SizedBox(
                                width: double.infinity,
                                height: 46,
                                child: ElevatedButton(
                                  onPressed: doneExercises > 0
                                      ? () => _showLogMinutesDialog(
                                          ctrl,
                                          dayIndex,
                                        )
                                      : null,
                                  style: ElevatedButton.styleFrom(
                                    backgroundColor: const Color(0xFF4F46E5),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                  child: const Text(
                                    'Complete Workout Day',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                ),
                              ),
                              const SizedBox(height: 8),
                            ] else ...[
                              Container(
                                padding: const EdgeInsets.symmetric(
                                  vertical: 10,
                                ),
                                width: double.infinity,
                                alignment: Alignment.center,
                                decoration: BoxDecoration(
                                  color: const Color(0xFFECFDF5),
                                  borderRadius: BorderRadius.circular(10),
                                  border: Border.all(
                                    color: const Color(0xFFA7F3D0),
                                  ),
                                ),
                                child: const Row(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: [
                                    Icon(
                                      Icons.check_circle,
                                      color: Color(0xFF10B981),
                                      size: 16,
                                    ),
                                    SizedBox(width: 8),
                                    Text(
                                      'Workout Logged & Completed!',
                                      style: TextStyle(
                                        color: Color(0xFF065F46),
                                        fontSize: 12,
                                        fontWeight: FontWeight.bold,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              const SizedBox(height: 8),
                            ],
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            );
          },
        ),
        if (week.days.isNotEmpty && !week.days.every((d) => d.isCompleted)) ...[
          const SizedBox(height: 16),
          SizedBox(
            width: double.infinity,
            height: 50,
            child: ElevatedButton(
              onPressed: () async {
                final confirm = await _showConfirm(
                  'Complete Week',
                  'Are you sure you want to mark this entire week as completed?',
                );
                if (confirm == true) {
                  final success = await ctrl.logWeekCompletion(widget.token);
                  if (success && mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content: Text('Week completed successfully!'),
                        backgroundColor: Color(0xFF10B981),
                      ),
                    );

                    // Open the next week automatically
                    final nextWeekIndex = ctrl.activePlan!.plan.indexWhere(
                      (w) => w.week > ctrl.selectedWeekNumber,
                    );
                    if (nextWeekIndex != -1) {
                      ctrl.setSelectedWeek(
                        ctrl.activePlan!.plan[nextWeekIndex].week,
                      );
                    }
                  } else if (!success && mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: Text(
                          ctrl.errorMessage ?? 'Failed to complete week.',
                        ),
                        backgroundColor: Colors.red,
                      ),
                    );
                  }
                }
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF10B981),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
              child: const Text(
                'Mark Week as Completed',
                style: TextStyle(
                  color: Colors.white,
                  fontWeight: FontWeight.bold,
                  fontSize: 16,
                ),
              ),
            ),
          ),
        ],
      ],
    );
  }

  void _showLogMinutesDialog(ClientTrainingPlanController ctrl, int dayIndex) {
    final durCtrl = TextEditingController(text: '45');
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: Colors.white,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        title: const Text(
          'Log Workout Time',
          style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'How long did this training session take in minutes?',
              style: TextStyle(color: Color(0xFF6B7280), fontSize: 13),
            ),
            const SizedBox(height: 12),
            TextField(
              controller: durCtrl,
              keyboardType: TextInputType.number,
              style: const TextStyle(color: Colors.black),
              decoration: InputDecoration(
                suffixText: 'mins',
                suffixStyle: const TextStyle(color: Color(0xFF4F46E5)),
                filled: true,
                fillColor: const Color(0xFFF9FAFB),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(10),
                ),
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Cancel', style: TextStyle(color: Colors.grey)),
          ),
          ElevatedButton(
            onPressed: () async {
              final mins = int.tryParse(durCtrl.text) ?? 45;
              Navigator.pop(ctx);
              final success = await ctrl.logDayCompletion(
                token: widget.token,
                dayIndex: dayIndex,
                durationMinutes: mins,
              );
              if (success && mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text('Workout logged successfully! Keep it up!'),
                    backgroundColor: Color(0xFF10B981),
                  ),
                );
              } else if (!success && mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text(
                      ctrl.errorMessage ?? 'Failed to log workout.',
                    ),
                    backgroundColor: Colors.red,
                  ),
                );
              }
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF4F46E5),
            ),
            child: const Text(
              'Save Log',
              style: TextStyle(
                color: Colors.white,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Future<bool?> _showConfirm(String title, String message) {
    return showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: Colors.white,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        title: Text(
          title,
          style: const TextStyle(
            color: Colors.black,
            fontWeight: FontWeight.bold,
          ),
        ),
        content: Text(message, style: const TextStyle(color: Colors.black87)),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: const Text('Cancel', style: TextStyle(color: Colors.grey)),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(ctx, true),
            style: ElevatedButton.styleFrom(backgroundColor: Colors.red),
            child: const Text(
              'Proceed',
              style: TextStyle(
                color: Colors.white,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
