// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeOAxiq9Oca6IwDRoZAPzT8z8-lpweuAo',
    appId: '1:8109205353:web:8d9538ae062fcf0aee7ff8',
    messagingSenderId: '8109205353',
    projectId: 'titan-app-a6c42',
    authDomain: 'titan-app-a6c42.firebaseapp.com',
    storageBucket: 'titan-app-a6c42.firebasestorage.app',
    measurementId: 'G-XJZYMTYGCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA47Iilt7u_HdLefDRHr46HJje7ceitxHA',
    appId: '1:8109205353:android:e57e1144a998d194ee7ff8',
    messagingSenderId: '8109205353',
    projectId: 'titan-app-a6c42',
    storageBucket: 'titan-app-a6c42.firebasestorage.app',
  );
}
