"""subscription table

Revision ID: ad0fa9c93938
Revises: 8f4208b33cd3
Create Date: 2026-06-21 03:29:08.896042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0fa9c93938'
down_revision: Union[str, Sequence[str], None] = '8f4208b33cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('subscriptionID', sa.Integer(), nullable=False),
    sa.Column('gymClientMebershipID', sa.Integer(), nullable=False),
    sa.Column('supscriptionPrice', sa.Integer(), nullable=False),
    sa.Column('duration_count', sa.Integer(), nullable=False),
    sa.Column('billingDate', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gymClientMebershipID'], ['gym_client_memberships.id'], ),
    sa.PrimaryKeyConstraint('subscriptionID')
    )
    op.create_index(op.f('ix_subscriptions_subscriptionID'), 'subscriptions', ['subscriptionID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_subscriptionID'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
