"""training plan model change

Revision ID: 87e27bdd03b4
Revises: c744a2ad5346
Create Date: 2026-06-23 13:49:42.726936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e27bdd03b4'
down_revision: Union[str, Sequence[str], None] = 'c744a2ad5346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_offer_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['gym_client_memberships.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['retention_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_offer_recipients_id'), 'retention_offer_recipients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retention_offer_recipients_id'), table_name='retention_offer_recipients')
    op.drop_table('retention_offer_recipients')
    # ### end Alembic commands ###
