"""gym machines update

Revision ID: 765b2b9cce67
Revises: 4041559d8102
Create Date: 2026-06-11 00:00:57.713020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765b2b9cce67'
down_revision: Union[str, Sequence[str], None] = '4041559d8102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machines_machineID'), table_name='machines')
    op.add_column('gym_machine_inventory', sa.Column('machineName', sa.String(), nullable=False))
    op.add_column('gym_machine_inventory', sa.Column('machineType', sa.String(), nullable=False))
    op.drop_constraint(op.f('gym_machine_inventory_machineID_fkey'), 'gym_machine_inventory', type_='foreignkey')
    op.drop_column('gym_machine_inventory', 'machineID')
    op.drop_column('gym_machine_inventory', 'status')
    op.drop_table('machines')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gym_machine_inventory', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('gym_machine_inventory', sa.Column('machineID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('gym_machine_inventory_machineID_fkey'), 'gym_machine_inventory', 'machines', ['machineID'], ['machineID'])
    op.drop_column('gym_machine_inventory', 'machineType')
    op.drop_column('gym_machine_inventory', 'machineName')
    op.create_table('machines',
    sa.Column('machineID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('machineName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('machineType', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('muscleGroup', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('machineID', name=op.f('machines_pkey'))
    )
    op.create_index(op.f('ix_machines_machineID'), 'machines', ['machineID'], unique=False)
    # ### end Alembic commands ###
