"""change in gym table

Revision ID: 1d271941d26a
Revises: a4bcf13c89fc
Create Date: 2026-05-18 18:06:14.667102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d271941d26a'
down_revision: Union[str, Sequence[str], None] = 'a4bcf13c89fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyms', sa.Column('yearlyRevenue', sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gyms', 'yearlyRevenue')
    # ### end Alembic commands ###
