"""added parameters to user table

Revision ID: ac2afe12296a
Revises: 8061ca43886a
Create Date: 2026-05-11 03:37:40.102001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2afe12296a'
down_revision: Union[str, Sequence[str], None] = '8061ca43886a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_exp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_exp')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
