"""gym table columns modifying

Revision ID: 84244a17112a
Revises: ad0fa9c93938
Create Date: 2026-06-21 03:45:34.417055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84244a17112a'
down_revision: Union[str, Sequence[str], None] = 'ad0fa9c93938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gyms', 'yearlySubscriptionPrice')
    op.drop_column('gyms', 'subscriptionPrice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyms', sa.Column('subscriptionPrice', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('gyms', sa.Column('yearlySubscriptionPrice', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
