"""changes in member invitation table

Revision ID: 8bf034223100
Revises: 84244a17112a
Create Date: 2026-06-21 05:38:16.194810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf034223100'
down_revision: Union[str, Sequence[str], None] = '84244a17112a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_invitations', sa.Column('subscription_price', sa.Integer(), nullable=True))
    op.add_column('member_invitations', sa.Column('duration_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_invitations', 'duration_count')
    op.drop_column('member_invitations', 'subscription_price')
    # ### end Alembic commands ###
