"""retention offer table

Revision ID: d3a8e47152cb
Revises: f3ba7ae32de9
Create Date: 2026-06-19 22:44:48.767937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a8e47152cb'
down_revision: Union[str, Sequence[str], None] = 'f3ba7ae32de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gymId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('offer_type', sa.Enum('discount', 'supplement', 'free_session', 'membership_upgrade', name='offertype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('benefit', sa.String(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('target_type', sa.Enum('highest_risk', 'lowest_risk', 'all_members', 'manual_selection', name='targettype'), nullable=False),
    sa.Column('number_of_members', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['gymId'], ['gyms.gymID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_offers_id'), 'retention_offers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retention_offers_id'), table_name='retention_offers')
    op.drop_table('retention_offers')
    # ### end Alembic commands ###
