"""cascading on delete in class request table

Revision ID: 2413a5a42233
Revises: e2b33229cf51
Create Date: 2026-07-03 02:40:46.478354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2413a5a42233'
down_revision: Union[str, Sequence[str], None] = 'e2b33229cf51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('retention_offers_gymId_fkey'), 'retention_offers', type_='foreignkey')
    op.create_foreign_key(None, 'retention_offers', 'gyms', ['gymId'], ['gymID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'retention_offers', type_='foreignkey')
    op.create_foreign_key(op.f('retention_offers_gymId_fkey'), 'retention_offers', 'gyms', ['gymId'], ['gymID'])
    # ### end Alembic commands ###
