"""add subscription fields to member_invitation

Revision ID: 4386b5325dbd
Revises: 76c41e08f1db
Create Date: 2026-06-19 06:03:59.164590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4386b5325dbd'
down_revision: Union[str, Sequence[str], None] = '76c41e08f1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_invitations', sa.Column('subscription', sa.String(), nullable=True))
    op.add_column('member_invitations', sa.Column('subscription_end', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_invitations', 'subscription_end')
    op.drop_column('member_invitations', 'subscription')
    # ### end Alembic commands ###
