"""announcements table

Revision ID: 692d280f21d7
Revises: aad3baf57631
Create Date: 2026-06-20 02:02:19.364956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692d280f21d7'
down_revision: Union[str, Sequence[str], None] = 'aad3baf57631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('reciever', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'reciever')
    # ### end Alembic commands ###
