"""cascading on delete in class request table

Revision ID: e2b33229cf51
Revises: a7776bc23eee
Create Date: 2026-07-03 02:38:19.142911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b33229cf51'
down_revision: Union[str, Sequence[str], None] = 'a7776bc23eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('class_requests_gymID_fkey'), 'class_requests', type_='foreignkey')
    op.create_foreign_key(None, 'class_requests', 'gyms', ['gymID'], ['gymID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class_requests', type_='foreignkey')
    op.create_foreign_key(op.f('class_requests_gymID_fkey'), 'class_requests', 'gyms', ['gymID'], ['gymID'])
    # ### end Alembic commands ###
