"""retention offer update

Revision ID: 6e1d33d80842
Revises: 7b81fcdbbfac
Create Date: 2026-07-02 18:36:34.200572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e1d33d80842'
down_revision: Union[str, Sequence[str], None] = '7b81fcdbbfac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retention_offers', 'offer_type',
               existing_type=postgresql.ENUM('discount', 'supplement', 'free_session', 'membership_upgrade', name='offertype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retention_offers', 'offer_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('discount', 'supplement', 'free_session', 'membership_upgrade', name='offertype'),
               existing_nullable=False)
    # ### end Alembic commands ###
