"""changing subscription table 

Revision ID: 610564668e80
Revises: 5b8ecf04ff7d
Create Date: 2026-06-24 01:52:35.162514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610564668e80'
down_revision: Union[str, Sequence[str], None] = '5b8ecf04ff7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('clientID', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('gymID', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('subscriptions_gymClientMebershipID_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'clients', ['clientID'], ['clientID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscriptions', 'gyms', ['gymID'], ['gymID'], ondelete='CASCADE')
    op.drop_column('subscriptions', 'gymClientMebershipID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('gymClientMebershipID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_gymClientMebershipID_fkey'), 'subscriptions', 'gym_client_memberships', ['gymClientMebershipID'], ['id'], ondelete='CASCADE')
    op.drop_column('subscriptions', 'gymID')
    op.drop_column('subscriptions', 'clientID')
    # ### end Alembic commands ###
