"""announcements table

Revision ID: aad3baf57631
Revises: d3a8e47152cb
Create Date: 2026-06-19 23:26:24.287482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad3baf57631'
down_revision: Union[str, Sequence[str], None] = 'd3a8e47152cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('announce_id', sa.Integer(), nullable=False),
    sa.Column('gymID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gymID'], ['gyms.gymID'], ),
    sa.PrimaryKeyConstraint('announce_id')
    )
    op.create_index(op.f('ix_announcements_announce_id'), 'announcements', ['announce_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcements_announce_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
