"""changing attendence table 

Revision ID: 6d8f32aa7119
Revises: d229786041c7
Create Date: 2026-06-24 22:47:05.006564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d8f32aa7119'
down_revision: Union[str, Sequence[str], None] = 'd229786041c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('gymID', sa.Integer(), nullable=False))
    op.add_column('attendance', sa.Column('clientID', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('attendance_membershipID_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'gyms', ['gymID'], ['gymID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attendance', 'clients', ['clientID'], ['clientID'], ondelete='CASCADE')
    op.drop_column('attendance', 'membershipID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('membershipID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_membershipID_fkey'), 'attendance', 'gym_client_memberships', ['membershipID'], ['id'], ondelete='CASCADE')
    op.drop_column('attendance', 'clientID')
    op.drop_column('attendance', 'gymID')
    # ### end Alembic commands ###
