"""cascading on deleting a row in the parent 

Revision ID: 5b8ecf04ff7d
Revises: 2e0f155384a2
Create Date: 2026-06-23 23:53:10.883676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8ecf04ff7d'
down_revision: Union[str, Sequence[str], None] = '2e0f155384a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('administrators_userID_fkey'), 'administrators', type_='foreignkey')
    op.create_foreign_key(None, 'administrators', 'users', ['userID'], ['userID'], ondelete='CASCADE')
    op.drop_constraint(op.f('announcements_gymID_fkey'), 'announcements', type_='foreignkey')
    op.create_foreign_key(None, 'announcements', 'gyms', ['gymID'], ['gymID'], ondelete='CASCADE')
    op.drop_constraint(op.f('attendance_membershipID_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'gym_client_memberships', ['membershipID'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('class_enrollments_session_id_fkey'), 'class_enrollments', type_='foreignkey')
    op.drop_constraint(op.f('class_enrollments_clientID_fkey'), 'class_enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'class_enrollments', 'class_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'class_enrollments', 'clients', ['clientID'], ['clientID'], ondelete='CASCADE')
    op.drop_constraint(op.f('class_sessions_coach_id_fkey'), 'class_sessions', type_='foreignkey')
    op.drop_constraint(op.f('class_sessions_gymID_fkey'), 'class_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'class_sessions', 'coaches', ['coach_id'], ['coachID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'class_sessions', 'gyms', ['gymID'], ['gymID'], ondelete='CASCADE')
    op.drop_constraint(op.f('clients_userID_fkey'), 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'users', ['userID'], ['userID'], ondelete='CASCADE')
    op.drop_constraint(op.f('coaches_userID_fkey'), 'coaches', type_='foreignkey')
    op.create_foreign_key(None, 'coaches', 'users', ['userID'], ['userID'], ondelete='CASCADE')
    op.drop_constraint(op.f('fcm_tokens_user_id_fkey'), 'fcm_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'fcm_tokens', 'users', ['user_id'], ['userID'], ondelete='CASCADE')
    op.drop_constraint(op.f('gym_client_memberships_clientID_fkey'), 'gym_client_memberships', type_='foreignkey')
    op.drop_constraint(op.f('gym_client_memberships_gymID_fkey'), 'gym_client_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'gym_client_memberships', 'clients', ['clientID'], ['clientID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'gym_client_memberships', 'gyms', ['gymID'], ['gymID'], ondelete='CASCADE')
    op.drop_constraint(op.f('gym_coach_memberships_gymID_fkey'), 'gym_coach_memberships', type_='foreignkey')
    op.drop_constraint(op.f('gym_coach_memberships_coachID_fkey'), 'gym_coach_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'gym_coach_memberships', 'gyms', ['gymID'], ['gymID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'gym_coach_memberships', 'coaches', ['coachID'], ['coachID'], ondelete='CASCADE')
    op.drop_constraint(op.f('gym_machine_inventory_gymID_fkey'), 'gym_machine_inventory', type_='foreignkey')
    op.create_foreign_key(None, 'gym_machine_inventory', 'gyms', ['gymID'], ['gymID'], ondelete='CASCADE')
    op.drop_constraint(op.f('gyms_adminID_fkey'), 'gyms', type_='foreignkey')
    op.create_foreign_key(None, 'gyms', 'administrators', ['adminID'], ['adminID'], ondelete='CASCADE')
    op.drop_constraint(op.f('member_invitations_gymID_fkey'), 'member_invitations', type_='foreignkey')
    op.create_foreign_key(None, 'member_invitations', 'gyms', ['gymID'], ['gymID'], ondelete='CASCADE')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['userID'], ondelete='CASCADE')
    op.drop_constraint(op.f('retention_offer_recipients_membership_id_fkey'), 'retention_offer_recipients', type_='foreignkey')
    op.drop_constraint(op.f('retention_offer_recipients_offer_id_fkey'), 'retention_offer_recipients', type_='foreignkey')
    op.create_foreign_key(None, 'retention_offer_recipients', 'gym_client_memberships', ['membership_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'retention_offer_recipients', 'retention_offers', ['offer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('subscriptions_gymClientMebershipID_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'gym_client_memberships', ['gymClientMebershipID'], ['id'], ondelete='CASCADE')
    op.add_column('training_plan_tracking', sa.Column('completed_exercises_list', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('training_plan_tracking_clientID_fkey'), 'training_plan_tracking', type_='foreignkey')
    op.drop_constraint(op.f('training_plan_tracking_planID_fkey'), 'training_plan_tracking', type_='foreignkey')
    op.create_foreign_key(None, 'training_plan_tracking', 'clients', ['clientID'], ['clientID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'training_plan_tracking', 'training_plans', ['planID'], ['planID'], ondelete='CASCADE')
    op.drop_constraint(op.f('training_plan_week_progress_clientID_fkey'), 'training_plan_week_progress', type_='foreignkey')
    op.drop_constraint(op.f('training_plan_week_progress_planID_fkey'), 'training_plan_week_progress', type_='foreignkey')
    op.create_foreign_key(None, 'training_plan_week_progress', 'clients', ['clientID'], ['clientID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'training_plan_week_progress', 'training_plans', ['planID'], ['planID'], ondelete='CASCADE')
    op.drop_constraint(op.f('training_plans_gym_id_fkey'), 'training_plans', type_='foreignkey')
    op.drop_constraint(op.f('training_plans_clientID_fkey'), 'training_plans', type_='foreignkey')
    op.create_foreign_key(None, 'training_plans', 'gyms', ['gym_id'], ['gymID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'training_plans', 'clients', ['clientID'], ['clientID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_plans', type_='foreignkey')
    op.drop_constraint(None, 'training_plans', type_='foreignkey')
    op.create_foreign_key(op.f('training_plans_clientID_fkey'), 'training_plans', 'clients', ['clientID'], ['clientID'])
    op.create_foreign_key(op.f('training_plans_gym_id_fkey'), 'training_plans', 'gyms', ['gym_id'], ['gymID'])
    op.drop_constraint(None, 'training_plan_week_progress', type_='foreignkey')
    op.drop_constraint(None, 'training_plan_week_progress', type_='foreignkey')
    op.create_foreign_key(op.f('training_plan_week_progress_planID_fkey'), 'training_plan_week_progress', 'training_plans', ['planID'], ['planID'])
    op.create_foreign_key(op.f('training_plan_week_progress_clientID_fkey'), 'training_plan_week_progress', 'clients', ['clientID'], ['clientID'])
    op.drop_constraint(None, 'training_plan_tracking', type_='foreignkey')
    op.drop_constraint(None, 'training_plan_tracking', type_='foreignkey')
    op.create_foreign_key(op.f('training_plan_tracking_planID_fkey'), 'training_plan_tracking', 'training_plans', ['planID'], ['planID'])
    op.create_foreign_key(op.f('training_plan_tracking_clientID_fkey'), 'training_plan_tracking', 'clients', ['clientID'], ['clientID'])
    op.drop_column('training_plan_tracking', 'completed_exercises_list')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_gymClientMebershipID_fkey'), 'subscriptions', 'gym_client_memberships', ['gymClientMebershipID'], ['id'])
    op.drop_constraint(None, 'retention_offer_recipients', type_='foreignkey')
    op.drop_constraint(None, 'retention_offer_recipients', type_='foreignkey')
    op.create_foreign_key(op.f('retention_offer_recipients_offer_id_fkey'), 'retention_offer_recipients', 'retention_offers', ['offer_id'], ['id'])
    op.create_foreign_key(op.f('retention_offer_recipients_membership_id_fkey'), 'retention_offer_recipients', 'gym_client_memberships', ['membership_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['userID'])
    op.drop_constraint(None, 'member_invitations', type_='foreignkey')
    op.create_foreign_key(op.f('member_invitations_gymID_fkey'), 'member_invitations', 'gyms', ['gymID'], ['gymID'])
    op.drop_constraint(None, 'gyms', type_='foreignkey')
    op.create_foreign_key(op.f('gyms_adminID_fkey'), 'gyms', 'administrators', ['adminID'], ['adminID'])
    op.drop_constraint(None, 'gym_machine_inventory', type_='foreignkey')
    op.create_foreign_key(op.f('gym_machine_inventory_gymID_fkey'), 'gym_machine_inventory', 'gyms', ['gymID'], ['gymID'])
    op.drop_constraint(None, 'gym_coach_memberships', type_='foreignkey')
    op.drop_constraint(None, 'gym_coach_memberships', type_='foreignkey')
    op.create_foreign_key(op.f('gym_coach_memberships_coachID_fkey'), 'gym_coach_memberships', 'coaches', ['coachID'], ['coachID'])
    op.create_foreign_key(op.f('gym_coach_memberships_gymID_fkey'), 'gym_coach_memberships', 'gyms', ['gymID'], ['gymID'])
    op.drop_constraint(None, 'gym_client_memberships', type_='foreignkey')
    op.drop_constraint(None, 'gym_client_memberships', type_='foreignkey')
    op.create_foreign_key(op.f('gym_client_memberships_gymID_fkey'), 'gym_client_memberships', 'gyms', ['gymID'], ['gymID'])
    op.create_foreign_key(op.f('gym_client_memberships_clientID_fkey'), 'gym_client_memberships', 'clients', ['clientID'], ['clientID'])
    op.drop_constraint(None, 'fcm_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fcm_tokens_user_id_fkey'), 'fcm_tokens', 'users', ['user_id'], ['userID'])
    op.drop_constraint(None, 'coaches', type_='foreignkey')
    op.create_foreign_key(op.f('coaches_userID_fkey'), 'coaches', 'users', ['userID'], ['userID'])
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key(op.f('clients_userID_fkey'), 'clients', 'users', ['userID'], ['userID'])
    op.drop_constraint(None, 'class_sessions', type_='foreignkey')
    op.drop_constraint(None, 'class_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('class_sessions_gymID_fkey'), 'class_sessions', 'gyms', ['gymID'], ['gymID'])
    op.create_foreign_key(op.f('class_sessions_coach_id_fkey'), 'class_sessions', 'coaches', ['coach_id'], ['coachID'])
    op.drop_constraint(None, 'class_enrollments', type_='foreignkey')
    op.drop_constraint(None, 'class_enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('class_enrollments_clientID_fkey'), 'class_enrollments', 'clients', ['clientID'], ['clientID'])
    op.create_foreign_key(op.f('class_enrollments_session_id_fkey'), 'class_enrollments', 'class_sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_membershipID_fkey'), 'attendance', 'gym_client_memberships', ['membershipID'], ['id'])
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.create_foreign_key(op.f('announcements_gymID_fkey'), 'announcements', 'gyms', ['gymID'], ['gymID'])
    op.drop_constraint(None, 'administrators', type_='foreignkey')
    op.create_foreign_key(op.f('administrators_userID_fkey'), 'administrators', 'users', ['userID'], ['userID'])
    # ### end Alembic commands ###
