"""class_request

Revision ID: 8061ca43886a
Revises: 2bfac6cf01d1
Create Date: 2026-05-08 13:39:20.516534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8061ca43886a'
down_revision: Union[str, Sequence[str], None] = '2bfac6cf01d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_requests', sa.Column('class_name', sa.String(), nullable=False))
    op.add_column('class_requests', sa.Column('gym_location', sa.String(), nullable=False))
    op.add_column('class_requests', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('class_requests', sa.Column('max_capacity', sa.Integer(), nullable=False))
    op.add_column('class_requests', sa.Column('reason_for_request', sa.String(), nullable=True))
    op.add_column('class_requests', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('class_requests', 'class_type')
    op.add_column('class_sessions', sa.Column('current_clients', sa.Integer(), nullable=True))
    op.add_column('class_sessions', sa.Column('max_clients', sa.Integer(), nullable=False))
    op.drop_column('class_sessions', 'current_students')
    op.drop_column('class_sessions', 'max_students')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_sessions', sa.Column('max_students', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('class_sessions', sa.Column('current_students', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('class_sessions', 'max_clients')
    op.drop_column('class_sessions', 'current_clients')
    op.add_column('class_requests', sa.Column('class_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('class_requests', 'created_at')
    op.drop_column('class_requests', 'reason_for_request')
    op.drop_column('class_requests', 'max_capacity')
    op.drop_column('class_requests', 'duration')
    op.drop_column('class_requests', 'gym_location')
    op.drop_column('class_requests', 'class_name')
    # ### end Alembic commands ###
