"""init database

Revision ID: 8254b224f7d5
Revises: 613855da4bfa
Create Date: 2026-05-19 02:20:06.097414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8254b224f7d5'
down_revision: Union[str, Sequence[str], None] = '613855da4bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_column('coaches', 'bio', if_exists=True)
    op.drop_column('coaches', 'specializations', if_exists=True)
    op.drop_column('coaches', 'years_experience', if_exists=True)
    op.drop_column('coaches', 'certifications', if_exists=True)
    op.drop_column('coaches', 'date_of_birth', if_exists=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('coaches', sa.Column('certifications', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('coaches', sa.Column('years_experience', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('coaches', sa.Column('specializations', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('coaches', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
