"""new tables

Revision ID: 613855da4bfa
Revises: fd34cdeea34a
Create Date: 2026-05-19 01:45:26.065556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613855da4bfa'
down_revision: Union[str, Sequence[str], None] = 'fd34cdeea34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('clientID', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('gymID', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('check_in_hour', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('check_in_date', sa.Date(), nullable=True))
    op.add_column('attendance', sa.Column('day_of_week', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'attendance', 'gyms', ['gymID'], ['gymID'])
    op.create_foreign_key(None, 'attendance', 'clients', ['clientID'], ['clientID'])
    op.drop_column('coaches', 'specializations')
    op.drop_column('coaches', 'years_experience')
    op.drop_column('coaches', 'bio')
    op.drop_column('coaches', 'certifications')
    op.drop_column('coaches', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('coaches', sa.Column('certifications', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('coaches', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('coaches', sa.Column('years_experience', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('coaches', sa.Column('specializations', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'day_of_week')
    op.drop_column('attendance', 'check_in_date')
    op.drop_column('attendance', 'check_in_hour')
    op.drop_column('attendance', 'gymID')
    op.drop_column('attendance', 'clientID')
    # ### end Alembic commands ###
