"""change in gym table

Revision ID: a4bcf13c89fc
Revises: c2f95bffd599
Create Date: 2026-05-18 16:51:08.421633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4bcf13c89fc'
down_revision: Union[str, Sequence[str], None] = 'c2f95bffd599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gyms', 'QRCode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gyms', 'QRCode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
