"""new tables

Revision ID: 19973112bd9b
Revises: e57a12bd2369
Create Date: 2026-05-13 23:42:13.616966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19973112bd9b'
down_revision: Union[str, Sequence[str], None] = 'e57a12bd2369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_client_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gymID', sa.Integer(), nullable=False),
    sa.Column('clientID', sa.Integer(), nullable=False),
    sa.Column('subscription', sa.String(), nullable=False),
    sa.Column('subscription_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', name='clientmembershipstatus'), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clientID'], ['clients.clientID'], ),
    sa.ForeignKeyConstraint(['gymID'], ['gyms.gymID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_client_memberships_id'), 'gym_client_memberships', ['id'], unique=False)
    op.create_table('member_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gymID', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='invitationstatus'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('invited_as', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gymID'], ['gyms.gymID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_member_invitations_id'), 'member_invitations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_invitations_id'), table_name='member_invitations')
    op.drop_table('member_invitations')
    op.drop_index(op.f('ix_gym_client_memberships_id'), table_name='gym_client_memberships')
    op.drop_table('gym_client_memberships')
    # ### end Alembic commands ###
