"""gym tables

Revision ID: e83c231405dd
Revises: ac2afe12296a
Create Date: 2026-05-13 17:50:33.409613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83c231405dd'
down_revision: Union[str, Sequence[str], None] = 'ac2afe12296a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('machineID', sa.Integer(), nullable=False),
    sa.Column('machineName', sa.String(), nullable=False),
    sa.Column('machineType', sa.String(), nullable=False),
    sa.Column('muscleGroup', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('machineID')
    )
    op.create_index(op.f('ix_machines_machineID'), 'machines', ['machineID'], unique=False)
    op.create_table('gyms',
    sa.Column('gymID', sa.Integer(), nullable=False),
    sa.Column('gymName', sa.String(), nullable=False),
    sa.Column('adminID', sa.Integer(), nullable=False),
    sa.Column('subscriptionPrice', sa.Double(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('QRCode', sa.String(), nullable=False),
    sa.Column('GYMTYPE', sa.String(), nullable=False),
    sa.Column('openingHours', sa.String(), nullable=False),
    sa.Column('closingHours', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['adminID'], ['administrators.adminID'], ),
    sa.PrimaryKeyConstraint('gymID')
    )
    op.create_index(op.f('ix_gyms_gymID'), 'gyms', ['gymID'], unique=False)
    op.create_table('gym_machine_inventory',
    sa.Column('inventoryID', sa.Integer(), nullable=False),
    sa.Column('gymID', sa.Integer(), nullable=False),
    sa.Column('machineID', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['gymID'], ['gyms.gymID'], ),
    sa.ForeignKeyConstraint(['machineID'], ['machines.machineID'], ),
    sa.PrimaryKeyConstraint('inventoryID')
    )
    op.create_index(op.f('ix_gym_machine_inventory_inventoryID'), 'gym_machine_inventory', ['inventoryID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gym_machine_inventory_inventoryID'), table_name='gym_machine_inventory')
    op.drop_table('gym_machine_inventory')
    op.drop_index(op.f('ix_gyms_gymID'), table_name='gyms')
    op.drop_table('gyms')
    op.drop_index(op.f('ix_machines_machineID'), table_name='machines')
    op.drop_table('machines')
    # ### end Alembic commands ###
