"""add member essential tables

Revision ID: 4029285aa713
Revises: 19973112bd9b
Create Date: 2026-05-14 12:20:47.900250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4029285aa713'
down_revision: Union[str, Sequence[str], None] = '19973112bd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_coach_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gymID', sa.Integer(), nullable=False),
    sa.Column('coachID', sa.Integer(), nullable=False),
    sa.Column('hire_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', name='coachmembershipstatus'), nullable=True),
    sa.ForeignKeyConstraint(['coachID'], ['coaches.coachID'], ),
    sa.ForeignKeyConstraint(['gymID'], ['gyms.gymID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_coach_memberships_id'), 'gym_coach_memberships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gym_coach_memberships_id'), table_name='gym_coach_memberships')
    op.drop_table('gym_coach_memberships')
    # ### end Alembic commands ###
