"""migration

Revision ID: f95c95e6cda7
Revises: 16d6eb4e47bc
Create Date: 2026-05-19 22:41:52.712501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f95c95e6cda7'
down_revision: Union[str, Sequence[str], None] = '16d6eb4e47bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'checked_in',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('attendance_clientID_fkey'), 'attendance', type_='foreignkey')
    op.drop_constraint(op.f('attendance_gymID_fkey'), 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'check_in_date')
    op.drop_column('attendance', 'clientID')
    op.drop_column('attendance', 'gymID')
    op.drop_column('attendance', 'check_in_hour')
    op.add_column('clients', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.drop_column('clients', 'profile_picture')
    op.drop_column('clients', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'date_of_birth')
    op.add_column('attendance', sa.Column('check_in_hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('gymID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('clientID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('check_in_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('attendance_gymID_fkey'), 'attendance', 'gyms', ['gymID'], ['gymID'])
    op.create_foreign_key(op.f('attendance_clientID_fkey'), 'attendance', 'clients', ['clientID'], ['clientID'])
    op.alter_column('attendance', 'checked_in',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
