"""class enrollment

Revision ID: 775cafbcbb95
Revises: f95c95e6cda7
Create Date: 2026-05-20 13:45:34.304155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775cafbcbb95'
down_revision: Union[str, Sequence[str], None] = 'f95c95e6cda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('clientID', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clientID'], ['clients.clientID'], ),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'clientID', name='unique_enrollment')
    )
    op.create_index(op.f('ix_class_enrollments_id'), 'class_enrollments', ['id'], unique=False)
    op.add_column('class_requests', sa.Column('gymID', sa.Integer(), nullable=True))
    op.add_column('class_requests', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('class_requests', sa.Column('day_of_week', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'class_requests', 'gyms', ['gymID'], ['gymID'])
    op.add_column('class_sessions', sa.Column('day_of_week', sa.String(length=10), nullable=True))
    op.add_column('class_sessions', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('class_sessions', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('class_sessions', sa.Column('gymID', sa.Integer(), nullable=True))
    op.alter_column('class_sessions', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'class_sessions', 'gyms', ['gymID'], ['gymID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class_sessions', type_='foreignkey')
    op.alter_column('class_sessions', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('class_sessions', 'gymID')
    op.drop_column('class_sessions', 'is_recurring')
    op.drop_column('class_sessions', 'duration')
    op.drop_column('class_sessions', 'day_of_week')
    op.drop_constraint(None, 'class_requests', type_='foreignkey')
    op.drop_column('class_requests', 'day_of_week')
    op.drop_column('class_requests', 'is_recurring')
    op.drop_column('class_requests', 'gymID')
    op.drop_index(op.f('ix_class_enrollments_id'), table_name='class_enrollments')
    op.drop_table('class_enrollments')
    # ### end Alembic commands ###
