"""class request model

Revision ID: 4688fe28483e
Revises: 775cafbcbb95
Create Date: 2026-05-21 01:21:53.703599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4688fe28483e'
down_revision: Union[str, Sequence[str], None] = '775cafbcbb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class_requests', 'gymID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('class_requests', 'requested_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('class_requests', 'gym_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_requests', sa.Column('gym_location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('class_requests', 'requested_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('class_requests', 'gymID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
