"""minor constraints changes

Revision ID: e046db7c343f
Revises: 706ffac0598d
Create Date: 2026-04-24 16:34:10.789045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e046db7c343f'
down_revision: Union[str, Sequence[str], None] = '706ffac0598d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_administrators_adminID'), 'administrators', ['adminID'], unique=False)
    op.create_index(op.f('ix_clients_clientID'), 'clients', ['clientID'], unique=False)
    op.create_index(op.f('ix_coaches_coachID'), 'coaches', ['coachID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coaches_coachID'), table_name='coaches')
    op.drop_index(op.f('ix_clients_clientID'), table_name='clients')
    op.drop_index(op.f('ix_administrators_adminID'), table_name='administrators')
    # ### end Alembic commands ###
