"""class_session

Revision ID: 2bfac6cf01d1
Revises: 27f1b69dfa90
Create Date: 2026-05-07 20:57:58.300196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bfac6cf01d1'
down_revision: Union[str, Sequence[str], None] = '27f1b69dfa90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_type', sa.String(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('requested_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.coachID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_requests_id'), 'class_requests', ['id'], unique=False)
    op.create_table('class_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('current_students', sa.Integer(), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.coachID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_sessions_id'), 'class_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_sessions_id'), table_name='class_sessions')
    op.drop_table('class_sessions')
    op.drop_index(op.f('ix_class_requests_id'), table_name='class_requests')
    op.drop_table('class_requests')
    # ### end Alembic commands ###
