"""migration

Revision ID: 23ae02cea321
Revises: 2b3c42e04356
Create Date: 2026-05-19 15:05:26.610681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ae02cea321'
down_revision: Union[str, Sequence[str], None] = '2b3c42e04356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('achievementID', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('chain_key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_emoji', sa.String(length=10), nullable=True),
    sa.Column('category', sa.Enum('CHECKIN', 'STREAK', 'CLASS', 'MILESTONE', 'TRAINING', name='achievementcategory'), nullable=False),
    sa.Column('difficulty', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'DIAMOND', name='achievementdifficulty'), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('prerequisite_key', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('achievementID')
    )
    op.create_index(op.f('ix_achievements_achievementID'), 'achievements', ['achievementID'], unique=False)
    op.create_index(op.f('ix_achievements_chain_key'), 'achievements', ['chain_key'], unique=False)
    op.create_index(op.f('ix_achievements_key'), 'achievements', ['key'], unique=True)
    op.create_table('client_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientID', sa.Integer(), nullable=False),
    sa.Column('achievementID', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('best_value', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['achievementID'], ['achievements.achievementID'], ),
    sa.ForeignKeyConstraint(['clientID'], ['clients.clientID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clientID', 'achievementID', name='uq_client_achievement')
    )
    op.create_index(op.f('ix_client_achievements_id'), 'client_achievements', ['id'], unique=False)
    op.create_table('training_plans',
    sa.Column('planID', sa.Integer(), nullable=False),
    sa.Column('clientID', sa.Integer(), nullable=False),
    sa.Column('parent_plan_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('goal', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('weeks', sa.Integer(), nullable=True),
    sa.Column('gym_id', sa.Integer(), nullable=True),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'PAUSED', 'ABANDONED', name='planstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clientID'], ['clients.clientID'], ),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.gymID'], ),
    sa.ForeignKeyConstraint(['parent_plan_id'], ['training_plans.planID'], ),
    sa.PrimaryKeyConstraint('planID')
    )
    op.create_index(op.f('ix_training_plans_planID'), 'training_plans', ['planID'], unique=False)
    op.create_table('training_plan_tracking',
    sa.Column('trackingID', sa.Integer(), nullable=False),
    sa.Column('clientID', sa.Integer(), nullable=False),
    sa.Column('planID', sa.Integer(), nullable=False),
    sa.Column('tracking_date', sa.Date(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('planned_exercises', sa.Integer(), nullable=True),
    sa.Column('completed_exercises', sa.Integer(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'PARTIAL', 'SKIPPED', 'PLANNED', name='workoutstatus'), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clientID'], ['clients.clientID'], ),
    sa.ForeignKeyConstraint(['planID'], ['training_plans.planID'], ),
    sa.PrimaryKeyConstraint('trackingID')
    )
    op.create_index(op.f('ix_training_plan_tracking_trackingID'), 'training_plan_tracking', ['trackingID'], unique=False)
    op.create_table('training_plan_week_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientID', sa.Integer(), nullable=False),
    sa.Column('planID', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=True),
    sa.Column('week_end_date', sa.Date(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('completed_days', sa.Integer(), nullable=True),
    sa.Column('skipped_days', sa.Integer(), nullable=True),
    sa.Column('average_completion', sa.Float(), nullable=True),
    sa.Column('week_status', sa.Enum('COMPLETED', 'IN_PROGRESS', 'PLANNED', name='daystatus'), nullable=True),
    sa.ForeignKeyConstraint(['clientID'], ['clients.clientID'], ),
    sa.ForeignKeyConstraint(['planID'], ['training_plans.planID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plan_week_progress_id'), 'training_plan_week_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_plan_week_progress_id'), table_name='training_plan_week_progress')
    op.drop_table('training_plan_week_progress')
    op.drop_index(op.f('ix_training_plan_tracking_trackingID'), table_name='training_plan_tracking')
    op.drop_table('training_plan_tracking')
    op.drop_index(op.f('ix_training_plans_planID'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_client_achievements_id'), table_name='client_achievements')
    op.drop_table('client_achievements')
    op.drop_index(op.f('ix_achievements_key'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_chain_key'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_achievementID'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
