"""coach data

Revision ID: a51d1e415228
Revises: 1f6275ebfad9
Create Date: 2026-06-10 18:41:54.946404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51d1e415228'
down_revision: Union[str, Sequence[str], None] = '1f6275ebfad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('coaches', sa.Column('specializations', sa.String(), nullable=True))
    op.add_column('coaches', sa.Column('certifications', sa.String(), nullable=True))
    op.add_column('coaches', sa.Column('years_experience', sa.Integer(), nullable=True))
    op.add_column('coaches', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaches', 'date_of_birth')
    op.drop_column('coaches', 'years_experience')
    op.drop_column('coaches', 'certifications')
    op.drop_column('coaches', 'specializations')
    op.drop_column('coaches', 'bio')
    # ### end Alembic commands ###
