"""client table database migration

Revision ID: f9dc73895fe2
Revises: 4029285aa713
Create Date: 2026-05-16 15:54:53.147692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9dc73895fe2'
down_revision: Union[str, Sequence[str], None] = '4029285aa713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('emergency_contact', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('profile_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'profile_picture')
    op.drop_column('clients', 'emergency_contact')
    op.drop_column('clients', 'bio')
    # ### end Alembic commands ###
