"""class enrollment model

Revision ID: 1f6275ebfad9
Revises: 4688fe28483e
Create Date: 2026-05-29 08:29:59.845632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6275ebfad9'
down_revision: Union[str, Sequence[str], None] = '4688fe28483e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_enrollments', sa.Column('class_date', sa.Date(), nullable=False))
    op.drop_constraint(op.f('unique_enrollment'), 'class_enrollments', type_='unique')
    op.create_unique_constraint('unique_enrollment_per_date', 'class_enrollments', ['session_id', 'clientID', 'class_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_enrollment_per_date', 'class_enrollments', type_='unique')
    op.create_unique_constraint(op.f('unique_enrollment'), 'class_enrollments', ['session_id', 'clientID'], postgresql_nulls_not_distinct=False)
    op.drop_column('class_enrollments', 'class_date')
    # ### end Alembic commands ###
